# Generated by Django 5.2.5 on 2025-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0018_remove_university_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("raw_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_tx_ref",
                    models.CharField(
                        blank=True,
                        help_text="Optional tx ref to bind with payment webhook",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="universitie_email_075501_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryJobSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("site_name", models.CharField(max_length=200)),
                ("site_url", models.URLField()),
            ],
            options={
                "verbose_name": "Country Job Site",
                "verbose_name_plural": "Country Job Sites",
                "ordering": ["country", "site_name"],
                "unique_together": {("country", "site_name")},
            },
        ),
    ]
